name: Sample Image

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3

    # output from main.tf
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/1067740512006/locations/global/workloadIdentityPools/example-pool/providers/example-gh-provider'
        service_account: 'my-service-account@glasnt-githubactions-4821.iam.gserviceaccount.com'

    - name: 'Deploy to Cloud Run'
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        image: 'gcr.io/cloudrun/hello'
        region: australia-southeast-2
        service: 'gday-cloud-run'